[buildPlans.iosevka-simsva]
family = "Iosevka Simsva"
spacing = "fontconfig-mono"
serifs = "slab"
no-cv-ss = false
no-ligation = false

[buildPlans.iosevka-simsva.variants.design]
capital-q = "crossing"
f = "tailed"
i = "serifed-flat-tailed"
l = "serifed-flat-tailed"
t = "standard-short-neck"
turn-v = "straight"
lower-alpha = "crossing"
one = "base"
five = "vertical-upper-left-bar"
six = "closed-contour"
seven = "curly-serifless"
nine = "closed-contour"
asterisk = "penta-low"
caret = "medium"
number-sign = "slanted"
ampersand = "upper-open"
dollar = "open-cap"
cent = "open"
percent = "rings-continuous-slash"
bar = "force-upright"
lig-ltgteq = "slanted"
ascii-grave = "straight"
question = "smooth"

[buildPlans.iosevka-simsva.variants.italic]
capital-h = "top-left-bottom-right-serifed"
capital-i = "short-serifed"
capital-j = "descending-serifed-symmetric"
capital-k = "curly-serifed"
capital-l = "serifed"
capital-r = "curly"
capital-v = "curly-motion-serifed"
capital-w = "curly-motion-serifed"
capital-x = "curly-serifed"
capital-y = "curly-serifed"
capital-z = "cursive"
f = "flat-hook-diagonal-tailed"
g = "double-storey-open"
h = "tailed"
i = "serifed-diagonal-tailed"
j = "diagonal-tailed-serifed"
l = "serifed-diagonal-tailed"
m = "tailed-top-left-serifed"
n = "tailed-motion-serifed"
q = "diagonal-tailed-motion-serifed"
r = "corner-hooked-top-serifed"
t = "diagonal-tailed-short-neck2"
v = "cursive-serifed"
w = "cursive"
z = "cursive"
ampersand = "lower-open"
ascii-single-quote = "raised-comma"
ascii-grave = "raised-turn-comma"

[buildPlans.iosevka-simsva.ligations]
inherits = "dlig"

# vim: ft=cfg
